name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}

api-version: 1.17

description: <3

author: TurtleException
website: https://eldritch.de

commands:
  click:
    description: Ändert die Partikel für einen bestimmten Spieler oder die Standard-Einstellung für Spieler, die keine zugewiesenen Partikel haben.
    usage: /click
  update:
    description: Ersetzt das Plugin durch eine neuere Version, falls eine entsprechende Datei vorhanden ist.
    usage: /update