name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}

api-version: 1.17

description: <3

author: TurtleException
website: https://eldritch.de

commands:
  turtlefly:
    description: All TurtleFly commands
    usage: /turtlefly <feature> <args>